version: '2'

services:
    web:
        build: .
        ports: 
            - "8000:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        ports: 
            - "1433:1433"
        environment:
            SA_PASSWORD: "Luis9000"
            ACCEPT_EULA: "Y"