version: '2'

services:
    web:
        build: .
        command: dotnet run
        ports: 
            - "5000:5000"
        links:
            - db
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        ports: 
            - "1433:1433"
        environment:
            SA_PASSWORD: "Luis9000"
            ACCEPT_EULA: "Y"